name: Terraform Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        working-directory: src
        run: terraform init

      - name: Run Terraform Validate
        working-directory: src
        run: terraform validate


      - name: Terraform Test
        working-directory: src
        run: terraform apply -auto-approve
